TheOdinProject/css-exercises

foundations/02-class-id-selectors/README.md

Should refer to `p` instead of `div` for the odd numbered elements

Fix typo in self check

---

flex/07-flex-layout-2/solution/solution.css

In the exercise Style.css, there was no width element added on the .card selector.
it's only added in the solution, so I think the width element should be moved to under the solution line.

Misplaced width ellement added after solving

---

foundations/04-chaining-selectors/index.html
foundations/04-chaining-selectors/solution/solution.html

Classes must now be chained properly to reach the desired outcome.

Remove hyphens from 04-chaining-selectors/index.html.

---

foundations/06-cascade-fix/style.css

Reverts TheOdinProject/css-exercises#81
Due to failing to update the picture, for the time being, reverting the change to keep accuracy with lesson information.

Revert "did the 06-cascade-fix"

---

margin-and-padding/margin-and-padding-2/README.md

`.button` was been changed to `.button-container`, but the readme file was not changed.

Fixed a typo at margin-and-padding-2/README.md

---

flex/03-flex-header-2/solution/solution.css

In this case, all elements are either in the .left or the .right container. The alignment is correctly set on the corresponding class, but also set on the header which might be misleading.

Remove redundant line

---

foundations/02-class-id-selectors/README.md
foundations/02-class-id-selectors/solution/solution.css

On Ubuntu 20.04.3 LTS with Firefox, the Verdana font isn't present.
The suggested sans serif font `DejaVu Sans` is commonly deployed as standard within popular Linux distributions such as Ubuntu, Debian, Fedora, and RHEL so should provide good usability.
I appreciate the CSS falls back to the system standard font for 'sans serif' if the named font isn't found, however specifying a font actually present on the system makes for a better learning experience on this occasion.
This could be a good example for future web developers, for consideration that the end-user of their web pages in real life might not be using the same OS/browser combination as them.

Foundations-002 Added Linux-compatible font

---

grid/01-grid-layout-1/solution/solution.css

This PR reverts the solution back to using pixels instead of `fr` units. This PR also changes the gap back to 15px to match the initial setup and screenshot.

Change solution back to pixels and fix gap

---

flex/07-flex-layout-2/README.md

**1. Description of the Changes**
I have added a hint about `.card` divs requiring their space to be defined so `wrap` works as intended. In this case it is going to be defining `width` property of them because of `flex-direction: row` of the container as asked in the Self-Check. 
I realize that the original issue asked for including in the self-check section:
* Ensure each card has a width of 300px
but I believe that might make people miss out on understanding why defining this space is needed. Instead of leaving learners with "it worked with cards being 300px! hooray!" I'd rather have people leave with "for wrap to work I need to tell it when to wrap and that means telling the items how much space they should take." 
Hopefully this is still in scope of this issue, I will gladly only …

07 flex layout 2: add additional hint for cards requiring space

---

grid/02-grid-layout-2/README.md

**1. Description of the Changes**
The desired-outcome.png shows a layout where the second column is three times larger than the first column. The README's Self Check portion has the two column sizes listed backwards.

Fixed typo in grid-layout-2 exercise

---

foundations/02-class-id-selectors/solution/solution.css

<hr>
Font names with whitespace should be put in quotes as per good practice recommended by TOP. This isn't the case here with `DejaVu Sans`.
Closes #132 
* Adds quotes to `DejaVu Sans` font 
**3. Additional …

02-class-id-selectors: Fix improper font-family syntax

---

foundations/05-descendant-combinator/solution/solution.css

<hr>
Closes #153 
-   [ ] Add other possible solutions comment to solutions.css file

05-descendant-combinator: Add full solution

---

foundations/06-cascade-fix/solution/solution.css

<hr>
Additional solution has wrong px size and could potentially be confusing
Hard to read description 
Changed 12px to 14px to match the correct px size
Wrapped lengthy description as instructed per TOP …

Easy Fix - css-exercises/foundation/06 cascade fix/solution/style.css -Typo and line wrap

---

grid/03-grid-layout-3/solution/solution.css

There is a text-align:center in the .container block under the /*SOLUTION*/ comment when there is already a text-align:center within the original .container block on line 7.
<hr>
Solution.css contains two .container blocks. …

03-grid-layout-3: Remove a duplicate line of code from solution.css

---

grid/03-grid-layout-3/solution/solution.css

-   [x] I have ensured that the TOP solution files match the Desired Outcome image
<hr>
Closes #XXXXX
**3. Additional Information:**

grid/03-grid-layout-3/solution/solution.css : the grid-template-row command seems unnecessary

---

flex/06-flex-layout/index.html
flex/06-flex-layout/solution/solution.html
foundations/04-chaining-selectors/index.html
foundations/04-chaining-selectors/solution/solution.html

-   [] I have ensured that the TOP solution files match the Desired Outcome image
<hr>
-Four html files were missing the alt attribute in the img tag. This compromises accessibility. In addition, the use of alternative texts is considered a good practice and should be encouraged whenever appropriate.
Closes …

Flex and Foundations: add alt text for accessibility (#201)

---

foundations/06-cascade-fix/style.css

[X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
[X] The title of this PR follows the `location of change: brief description of change` format, e.g. `01-flex-center: Update self check`
The solution.css has a font weight of 800 on the classes `.para, small-para`, `.small-para`, and `.child` that were missing from the originally assigned style.css

06-cascade-fix: Add missing weight from solution.css

---

foundations/02-class-id-selectors/solution/solution.css
foundations/02-class-id-selectors/solution/solution.html

Third and fourth elements share the same declaration of font-size.
-   [x] I have ensured that the TOP solution files match the Desired Outcome image
<hr>
The third and fourth element share the same declaration for font-size of 24px and since the formerly class 'oddly-cool' already declared it, I removed the …

02-class-id-selectors: Change solution

---

foundations/02-class-id-selectors/README.md

There is often confusion about whether or not students have solved 02-class-id-selectors correctly, as the final display of index.html can vary wildly based on which fonts the student has installed. 
* Tweaks the wording of the 02-class-id-selectors note to make it clear that as long as the fonts are being properly added it doesn't matter if desired-outcome.png looks different.
Discussed on Discord at https://discord.com/channels/505093832157691914/1041342225201778769
-   [x] The `Because` …

02-class-id-selectors: Tweak note wording to make it clearer that desired-outcome.png isn't leading

---

flex/05-flex-modal/index.html
flex/05-flex-modal/solution/solution.css
flex/05-flex-modal/solution/solution.html
flex/05-flex-modal/style.css

Button element is technically better than `div` element when it's purpose is click event. In this case to close modal. 
1. `div` element replaced with `button` element
1.  `button` element now has cursor pointer to better accessibility
1.   new replaced `button` is identical as it was with `div` element
2.  associated css added for new enhancement
Closes #310 
-   [x] The `This PR` section has a bullet point list describing the …

#310 button element enhancement

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
README.md

- We are centralizing to https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md as the single source of truth for CONTRIBUTING.md
- Changes all https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md links to https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md
Part of TheOdinProject/theodinproject#3901
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `This PR` section has a bullet point list describing the …

Chore: repoint contributing links to .github/CONTRIBUTING.md

---

flex/06-flex-layout/solution/solution.css

- This is to keep with the flex spirit
- Another solution might instead be to nest .input and .buttons into their own container, then apply the gap property to that container. This solves the visually uneven spacing between <img> and .input
README.md says "There is space between the logo, input and buttons", but the related solution.css only gives space between the input and buttons via "margin-bottom: 16px;" applied to .input
This improves clarity of the README.md "Self Check" section by adding actual CSS "space between the logo, input and buttons", instead of the current arrangement with space only between the input and buttons. 
- remove `margin-bottom: 16px;` from `.input`
- use `gap: 16px` instead on their container: `.content`
Closes #349
-   [x] I have thoroughly read and …

flex: 06-flex-layout: README.md: Improve self check clarity

---

foundations/05-descendant-combinator/solution/solution.css

It gives beginners another option they could use as a selector for in their CSS if they prefer.
- Another CSS selector option, div > p
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section

05-descendant-combinator: Add css selector option

---

README.md

People are very commonly concerned when they see their exercise solutions differ from the provided solutions. This is primarily from two parts:
- Learners are initially directed straight to the relevant exercise directory and not told to read the repo README (where a note about the provided solution is). *This has been addressed in [#27055](https://github.com/TheOdinProject/curriculum/pull/27055)*
- The README note on provided solutions, despite saying the provided one isn't the only solution, the rest of the sentence seems to be interpret-able as "if your solution differs, check with the community if it's actually allowed".
- Improves the wording of the relevant README note to clarify intent (unified wording with `javascript-exercises` repo)
Closes …

Repo README: Improve wording regarding TOP provided solution

---

flex/02-flex-header/README.md
flex/02-flex-header/solution/solution.css

- The font in the desired image varies when compared with the solution's font.
- Added the specific font in the `solution.html`
Closes #458 
- Note: The `import` statement needs to be at the top of `css` file, so it couldn't be placed after `/* SOLUTION */` comment
-   [x] …

02-flex-header: Match the solution font with the desired image

---

flex/07-flex-layout-2/solution/solution.css

In `solution.css`, adding `gap` property to the parent `.container` class, instead of adding margin to the child `.card` class since we are using `Flexbox` for creating the cards. 
- Removing `margin: 16px`  from the `.card` class.
- Instead, adding `gap: 16px` property to the `.container` class to give space between the cards.
Closes #XXXXX
-   [x] If …

07-flex-layout-2: Add gap to container class instead of adding margin to card class in solution.css

---

README.md

Adds a bit more verbiage to encourage learners to use git workflow for these exercises but not to submit a PR.
- Add paragraph to intro of readme
Closes #465

README: add more info about git workflow and not to open PR

---

foundations/05-descendant-combinator/solution/solution.css

The div > p option in `solution.css` file is listed as a possible descendant combinator. According to MDN, it is not a descendant combinator, and it actually enforces stricter inheritance between parent and child element relationships, therefore it should not be listed as a possible combinator.
- Removes child combinator from the list of possible descendant combinators
Closes [#558](https://github.com/TheOdinProject/css-exercises/issues/558)
None.
-   [x] The `Because` section summarizes the reason …

05-descendant-combinator: Remove child combinator from solution.css

---

foundations/03-grouping-selectors/README.md
foundations/03-grouping-selectors/solution/solution.css

In the [Grouping Selectors](https://github.com/TheOdinProject/css-exercises/tree/main/foundations/03-grouping-selectors) module of the `foundations` folder, the desired-outcome.png file (and thus the README.md image) does not correctly convey the bold weight of the first button. This PR undoes the work done in #355, and fixes the expectation of having a bold button.
- Removes the bold requirement from README.md,
- Modifies the solution CSS.
Closes #559
None.
-   [x] The `Because` section summarizes …

03-grouping-selectors: Update CSS solutions and README.md for grouping selectors

---

foundations/cascade/01-cascade-fix/README.md
foundations/cascade/01-cascade-fix/solution/solution.css

A new way to solve the last part of the CSS Cascade exercise has been added, as a comment, in the solution file solution.css. That last part refers to the last rules to be modified (div.text and .child).
The README.md file in the 01-cascade-fix exercise says that all possible solutions to the exercise would be included (or at least it would try to do it). As I saw another possible solution for the last part of the exercise (div.text & .child associated rules), I decided to include it in the solution.css file.
- Under the explanation in line 87 of solution.css:
> _Then we added another selector to create a descendant combinator. If we only created a descendant combinator, the specificity would be tied with the div.text selector and it would come down to rule order, and if we only moved it, …

01-cascade-fix: Clarify multiple solutions in README
