foundations/01-css-methods/README.md

Slight Spelling mistake in Foundation -> README

Spelling error fixed

---

margin-and-padding/margin-and-padding-1/index.html

Added missing closing bracket on final div. (Sorry if this is the wrong way to do this, I'm new and here on assignment from The Odin Project.)

Closed final div

---

foundations/01-css-methods/README.md
foundations/02-class-id-selectors/README.md
foundations/04-chaining-selectors/README.md
foundations/05-descendant-combinator/README.md
foundations/06-cascade-fix/README.md

Spotted a few minor typos and little grammatical bugs in the README files of the foundations folder and changed them accordingly.

fixed some typos and minor grammatical changes

---

margin-and-padding/margin-and-padding-2/index.html
margin-and-padding/margin-and-padding-2/solution/solution.html

added closing bracket to div on line 15. Both on index.html and solution.html

add closing bracket

---

foundations/01-css-methods/solution/solution.css

As learners are reading the requirement for exercises, they will tend to follow the order of requirements listed when styling elements, so it makes sense for the solution to match the same order.

Changing the order of solution css file

---

README.md

A checklist so people can keep track of exercises they finished if they do not finish the entire exercise file in one sitting.

Added a checklist for the exercises

---

README.md

Saw that there is a bit confusion in git help channel, and frankly had the same question. Makes sense to clarify.

Clarifying how to get this repo

---

flex/02-flex-header/README.md
flex/03-flex-header-2/README.md
flex/04-flex-information/README.md
flex/05-flex-modal/README.md
flex/06-flex-layout/README.md
flex/07-flex-layout-2/README.md

No changes for the 01 exercise README.

Fix punctuation and grammar in Flex READMEs

---

margin-and-padding/margin-and-padding-1/README.md

The file to be edited in this exercise (margin-and-padding-1) is 'style.css' not 'index.html'.

Changed 'index.html' to 'style.css'

---

flex/04-flex-information/style.css

Found a minor typo in the style.css of 04-flex-information project. Typo was a 2nd ; on the align-items of style.css, line 23.

Fixed Typo, accidental 2nd ; on align-items

---

foundations/06-cascade-fix/style.css

1 - Fixed the colour to blue and green as per the need of colour blindness problem.
2 - Completed the css styling for the project on raised issue.

did the 06-cascade-fix

---

README.md

Suggested simple fix for issue detailed well here: https://github.com/TheOdinProject/css-exercises/issues/93

Added sentence in "Readme" directing user to GitHub docs re: 'forking'

---

flex/06-flex-layout/README.md

I have added a hint implicitly telling what to search for when it comes to getting rid of the underscore from link text. The reasoning is as follows:
Depending on how a user approaches the problem of the underscore they might turn to Google or Discord with two different questions - one being a direct one, "how to get rid of an underscore in a link?", the other more general, "how can links be styled?". I believe that the first one is the one that most people are going to ask and I can personally attest to asking Google such question. 
Why would we want users to ask the second question? So they can get acquainted with states and the fact that they can be separately styled, this broadens their knowledge of the CSS possibilities while still giving them the answer they're looking for.
This …

Add hint towards searching for styling links in 06-flex-layout exercise

---

grid/01-grid-layout-1/README.md

**1. Description of the Changes**
The fourth item on Self Check section was incorrect. It was stating "-The first column is three times larger than the other", when the second column should be three times larger than the first.
**2. Related Issue**
[Closes #120](https://github.com/TheOdinProject/css-exercises/issues/120)

01 grid layout 1: Modify Self Check item on README.md

---

grid/03-grid-layout-3/README.md

**1. Description of the Changes**
The Self Check in the README for this exercise said to nest a grid container into the `header` grid container, like so:
```md
- The header element has two columns
- The header element contains another grid that has two columns
```
The solution on the other hand creates four columns, like so:
```css
.menu ul {
display: grid;
grid-template-columns: 1fr 1fr 1fr 1fr;
}
```
I don't particularly think the `.menu ul` container necessitates grid, but I also understand how doing so may help reinforce the concept. For this reason, I chose only to update the Self Check to reflect the solution.
**2. Related Issue**
Closes #XXXXX

CSS Grid Exercise 03-grid-layout-3: Amend README

---

grid/02-grid-layout-2/README.md

<hr>
I am proposing removing the wording of "This is easy" from the exercise introduction. This may be demotivating for someone who is having difficulty with these concepts.

02-grid-layout-2: Update README.md

---

flex/06-flex-layout/index.html
flex/06-flex-layout/solution/solution.html
flex/07-flex-layout-2/index.html
flex/07-flex-layout-2/solution/solution.html

<hr>
Closes #154, Closes #155 
- Fix broken link with href="#" to every anchor.

flex/06+07: Fix broken links

---

grid/03-grid-layout-3/solution/solution.css

Both selectors were doing the same thing and were right next to each other, figured it may be cleaner to consolidate the code by combining the selectors.
-   [x] I have ensured that the TOP solution files match the Desired Outcome image
<hr>
Closes #XXXXX
**3. Additional Information:**

03-grid-layout-3 Update solutions.css

---

grid/03-grid-layout-3/README.md

<hr>
Part of Issue #170
Requires PR #173 to also be merged
- Removes old hint for not needing to add CSS selectors
- Adds new hint at top of list for adding CSS descendant blocks and how to find them
**3. …

03-grid-layout-3: Change hint wording for adding CSS declaration blocks

---

grid/03-grid-layout-3/solution/solution.css
grid/03-grid-layout-3/style.css

-   [x] I have ensured that the TOP solution files match the Desired Outcome image
<hr>
This PR closes an open issue. Closes #170. 
https://github.com/TheOdinProject/css-exercises/issues/170
**3. Additional Information:**

This Commit fixes #170 opened issue

---

foundations/06-cascade-fix/solution/solution.css

-   [X] I have ensured that the TOP solution files match the Desired Outcome image
<hr>
Closes #XXXXX
This PR updates the comments in the solution.css file to match recent changes to the exercise that replaced the red/green text with bold/thin text.
> Updates solution.css comments by adding …

Foundations/06-cascade-fix: Update solution comments

---

grid/03-grid-layout-3/index.html

<hr>
Adds a closing p tag to increase readability/avoid any confusion
Fixes a very small syntax error
**3. Additional Information:**

03-grid-layout-3: Add closing p tag to line 97

---

flex/07-flex-layout-2/solution/solution.css
flex/07-flex-layout-2/style.css

The instructions indicate the sidebar div to be 300px whereas it was found that it's 332px in ``solution.css``
- Changes the ``box-sizing`` property of the .sidebar to ``border-box``
Closes https://github.com/TheOdinProject/css-exercises/issues/269
-   [x] If …

flex/07-flex-layout-2 : fix solution.css inconsistency

---

flex/03-flex-header-2/README.md

In the previous exercise we already had to nest a flex container inside of another, so this is not the first time we are doing it.
In the previous exercise we already had to nest a flex container inside of another, so this is not the first time we are doing it. Before I fixing it, the description says this is the first time we are doing it (nesting flex containers)
- Juse the line 7 on 'README.md' being change from "This is also the first example where you'll be nesting flex containers inside each other." to "Just like you did in the previous exercise with the `ul`, you'll be nesting flex containers inside each other."
Closes #XXXXX …

Fix exercise description

---

animation/02-pop-up/script.js

Just a simple cleanup by removing duplicate element selector and maintaining the general styling of the project.
- Removed duplicate getElementById
- Added missing semicolon to norm styling of the script
Closes #303 
-   [X] The `Because` section summarizes the reason for this PR
-   [X] The `This PR` section has a bullet point list describing the changes in this PR
-   [X] If this PR addresses an open issue, it is linked in the `Issue` section
-   [X] If applicable, I have ensured that the TOP …

removed duplicate element selector & added semicolon

---

flex/05-flex-modal/README.md
flex/05-flex-modal/solution/solution.css
flex/05-flex-modal/solution/solution.html

I updated the solution.css and solution.html files in order to highlight the changes made to the containers and what they surround. In addition, I added an additional hint to the readme to hint that one might need to change the html to get the exact style
- updated solution.css file with a comment showing that changing header container is needed
- added comment to solution.html to show the changes in header div and container div
- added hint to readme to help user figure out what needs to be changed
Closes #248 
-   [ x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ x] The title of this PR follows the `location of change: brief description of change` format, e.g. …

05-Flex Modal: add comments and hints to solution files

---

foundations/04-chaining-selectors/README.md

Update link to artist profile, the one provided was broken/linking to a non-existing acc.
Just change [Katho Mutodo](https://www.pexels.com/@photobykatho?utm_content=attributionCopyText&utm_medium=referral&utm_source=pexels) to [Katho Mutodo](https://linktr.ee/photobykatho_) .
Closes #341
-   [x] If this PR addresses an open issue, it is linked in the …

04-chaining-selectors : Update link to artist Katho Mutodo profile

---

animation/02-pop-up/solution/solution.css
animation/02-pop-up/style.css

- the syntax wasn't consistent
- add `;` and insert line between `.popup-modal` and `popup-modal p`
Closes #XXXXX
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section

css-exercise animation 02 - edit syntax

---

README.md

Closes #XXXXX
-   [x] If applicable, I have ensured that the TOP solution files match the Desired Outcome image

 Improvement to enhance  its readability

---

foundations/01-css-methods/README.md

Fixes typo in a header.
- Edit 'quick tip' to 'Quick tip'
Closes #XXXXX
-   [x] If applicable, I have ensured that the TOP solution files match the Desired Outcome image

foundations-01-css-methods: Update README.md

---

foundations/06-cascade-fix/solution/solution.css

Line 88 was missing a comma.
1. Add a comma.
-   [x] If applicable, I have ensured that the TOP solution files match the Desired Outcome image

06-cascade-fix: Add a punctation mark

---

foundations/06-cascade-fix/README.md

There is a note at the bottom of the README of the Foundations-06 exercise regarding accessibility. A student had expressed confusion regarding accessibility. Given that accessibility is taught much later in the Javascript course (in the Advanced CSS/HTML section), this note is confusing to learners as they have not encountered accessibility yet. Thus this note should be removed.
- Removed the note at the bottom of the README of the Foundations 06 exercise on Cascade.
Closes #443
-   [x] The `Because` …

Foundations 06: Remove Unnecessary Accessibility Note

---

flex/07-flex-layout-2/README.md

Emojis might show up as text symbols instead of how they are shown in the Desired Outcome images, if the Noto Color Emoji font family is not properly installed. Some learners may seek to replicate the "Desired Outcome" exactly, but the emojis are not a necessary part of the exercise.
- Added disclaimer note to "Desired Outcome" section
Closes [#474](https://github.com/TheOdinProject/css-exercises/issues/474)
-   [x] The `This PR` section …

07-flex-layout-2: Add disclaimer to Desired Outcome

---

foundations/03-grouping-selectors/README.md

Update first two paragraphs of README to improve readability
- Remove redundant words
- Combine first two paragraphs
Closes #475 

03-grouping-selectors README: Update first two paragraphs

---

animation/02-pop-up/solution/solution.js

There is an extra line of code in the solution that is unnecessary which may confuse learners.
- Remove first backdrop assignment
Closes #363
-   [x] If applicable, I have ensured that the TOP solution files match the Desired Outcome image

Animation - pop-up: remove superfluous line of code in solution

---

flex/07-flex-layout-2/README.md

Since commit 65b831b changed the padding of cards `container` in `solution.css`, the instruction of padding in `README.md` should be consistent.
* Update the padding of 'cards' section from `32px` to `48px`. 
Closes #XXXXX
Although commit 65b831b changed margin size of every card as well, it's fine because there is nothing about margin size of cards in `README.md`.
-   [x] The `This PR` section has a bullet point list describing the …

07-flex-layout-2: Update README.md for consistency with solution.css

---

flex/06-flex-layout/style.css

Since commit 061fe0a replaced the margin with gap in `solution.css`, the margin should be deleted in `style.css` as well.
* remove `margin-bottom: 16px;` from `style.css`.
Closes #XXXXX
-   [x] If applicable, I have ensured that the TOP solution files match the Desired …

06-flex-layout: remove margin in style.css

---

README.md

I think it's nice to have this note stand out some from the other text in the README.
- Have the PR note in an "Important"  notebox
Closes #XXXXX
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section

README: Change style of PR note

---

intermediate-html-css/advanced-grid/01-responsive-holy-grail/README.md

Last two points of self check were a bit confusing. 
- Modified last 2 self checks of 01-responsive-holy-grail
Closes #606 
-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [X] The `Because` section summarizes the reason for this PR
-   [X] The `This PR` section has a bullet point list describing the changes in this PR
-   [X] If this PR addresses an open issue, it is linked in the `Issue` section
-   [X] If applicable, I have ensured that the TOP solution files match the Desired Outcome image

Grid:01-responsive-holy-grail modified README.md

---

foundations/cascade/01-cascade-fix/README.md

This is not the 'final' exercise for CSS Foundations, as README suggests. Because '01-margin-and-padding-1' and '02-margin-and-padding-2' are the last exercises for CSS Foundations, this README's wording needs to be updated for accuracy.
Because '01-margin-and-padding-1' and '02-margin-and-padding-2' are the last exercises for CSS Foundations, this README's wording needs to be updated for accuracy.
- Changed word 'final' to 'next'.
- …

01-cascade-fix: Fix typo in README

---

foundations/intro-to-css/02-class-id-selectors/style.css
foundations/intro-to-css/03-grouping-selectors/style.css
foundations/intro-to-css/05-descendant-combinator/style.css

A placeholder comment was added to the style.css for exercise 04-chaining-selectors (see commit - 21e874657913f91c5bbef1cf3d19a0b2dcd9c48a), but was not added to the other empty template style.css files. Adding it in for consistency.
Add placeholder comments to the empty style.css template files for the intro exercises.
-   [ ] If this PR addresses an …

intro-to-css: Add placeholder comments to style.css

---

README.md

Makes clearer that the provided solutions are only examples, not an ideal that's expected or intended as a "comparison for marking".
- Rephrases wording around provided solution in the repo README
Closes #XXXXX
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `01_helloWorld: Update test cases`
-   [x] If this PR includes any changes that affect the solution …

Clarify language in repo README about solutions
